name: Run Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config expect curl zip unzip tar git
    
    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        echo "CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
    
    - name: Cache CMake build
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-cmake-v2-${{ hashFiles('CMakeLists.txt', 'src/**/*', 'vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-cmake-v2-
          ${{ runner.os }}-cmake-
    
    - name: Run tests
      run: ./run_tests.sh
      env:
        CI: true
        DEBIAN_FRONTEND: noninteractive
